### ISSUE TITLE
add-migration FAILS, also running the application produces error

### ISSUE THREAD

**Issue by JohnnyB77** [csharpschool/AspNetCoreVideo#10]
I bought the book and am working though it page by page but I am currently stuck in page 94.  When I add the migration I get an error shown below.

Unable to create an object of type 'VideoDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<VideoDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.

I also tried running the code downloaded from github and I get the following error from the browser.

An unhandled exception occurred while processing the request.
ArgumentNullException: Value cannot be null.
 Parameter name: connectionString

Any assistance is much appreciated.  Thank you.

John

**Comment by teemurgroup** [comment]
Are you running Core 2.0? I got stuck on the first add-migration command with the same error. After some considerable Googling I found this:
https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/

Seems there were some significant changes on the Program.cs file and if you built on the older version this causes an issue. I changed the file to match and it worked fine.

I also downloaded the source code from here - the NullException you are getting is because you don't have the secrets.json file created - it doesn't download with the source so you'll have to create that on your own. Once you do then it should compile.

**Comment by JohnnyB77** [comment]
I created the secrets.json file and it is giving me the exception. 

An unhandled exception occurred while processing the request.
InvalidOperationException: Can not find assembly file Microsoft.CSharp.dll 

In any case,  thank you teemurgroup for helping me out.  I followed your guidance and edited my project as per the link you provided and it now works.  I can now move forward with the rest of the book.  Thanks again, truly appreciate it.
